// =============================================================================
//  NODEWAVE — @nodewave/core — Config Schema & Helpers
// =============================================================================

import { fsx as fs } from './fsx.js';
import path from 'node:path';
import { z } from 'zod';
import type { ProjectType } from './detectors/project-type.js';

const CONFIG_FILE = 'nodewave.config.js';

export const NodewaveConfigSchema = z.object({
  project: z.string(),
  type: z.enum(['nextjs-app', 'nextjs-pages', 'express', 'fastify', 'unknown']),
  target: z.enum(['vercel', 'netlify', 'railway']).default('vercel'),
  build: z.object({
    command: z.string(),
    output: z.string(),
  }),
  env: z.object({
    required: z.array(z.string()).default([]),
    optional: z.array(z.string()).default([]),
  }).default({ required: [], optional: [] }),
  deploy: z.object({
    region: z.string().default('iad1'),
    nodeVersion: z.string().default('22'),
  }).default({ region: 'iad1', nodeVersion: '22' }),
});

export type NodewaveConfig = z.infer<typeof NodewaveConfigSchema>;

export async function loadConfig(cwd: string): Promise<NodewaveConfig | null> {
  const configPath = path.join(cwd, CONFIG_FILE);
  if (!await fs.pathExists(configPath)) return null;

  // Dynamic import for ESM config files
  const configUrl = new URL(`file://${configPath}`);
  const mod = await import(configUrl.href) as { default?: unknown };
  const raw = mod.default ?? mod;
  return NodewaveConfigSchema.parse(raw);
}

export async function saveConfig(config: NodewaveConfig, cwd: string): Promise<void> {
  const configPath = path.join(cwd, CONFIG_FILE);
  const content = `// nodewave.config.js — generated by nodewave
export default ${JSON.stringify(config, null, 2)};
`;
  await fs.writeFile(configPath, content, 'utf8');
}

export function generateDefaultConfig(opts: {
  name: string;
  type: ProjectType;
  target: 'vercel' | 'netlify' | 'railway';
}): NodewaveConfig {
  const buildMap: Record<ProjectType, { command: string; output: string }> = {
    'nextjs-app':   { command: 'next build', output: '.next' },
    'nextjs-pages': { command: 'next build', output: '.next' },
    'express':      { command: 'tsc', output: 'dist' },
    'fastify':      { command: 'tsc', output: 'dist' },
    'unknown':      { command: 'npm run build', output: 'dist' },
  };

  return {
    project: opts.name,
    type: opts.type,
    target: opts.target,
    build: buildMap[opts.type],
    env: { required: [], optional: [] },
    deploy: { region: 'iad1', nodeVersion: '22' },
  };
}
